# Guia de ejercicios

# Ejercicio 16 DataFrame de estudiantes

In [5]:
import pandas as pd

datos_estudiantes = {
    'nombre': ['Carlos', 'Ana', 'Luis', 'Sofia', 'Fernando', 'Maria', 'Jorge', 'Elena', 'Ricardo', 'Beatriz'],
    'carrera': ['Sistemas', 'Medicina', 'Sistemas', 'Derecho', 'Industrial', 'Medicina', 'Sistemas', 'Derecho', 'Industrial', 'Sistemas'],
    'edad': [21, 23, 20, 22, 24, 21, 22, 20, 25, 23],
    'promedio': [85.5, 92.0, 78.0, 88.5, 65.0, 90.0, 81.5, 74.0, 89.0, 95.5],
    'ciudad': ['Tegucigalpa', 'San Pedro Sula', 'Tegucigalpa', 'La Ceiba', 'Choluteca', 'San Pedro Sula', 'Comayagua', 'Tegucigalpa', 'La Ceiba', 'Santa Rosa']
}

df = pd.DataFrame(datos_estudiantes)

print("--- 3. Muestre las primeras 5 filas ---")
display(df.head(5)) 

print("\n--- 4. Muestre la información general del DataFrame ---")
df.info()

print("\n--- 5. Calcule el promedio general de calificaciones ---")
promedio_general = df['promedio'].mean()
print(f"El promedio general de todos los estudiantes es: {promedio_general:.2f}")

print("\n--- 6. Muestre estudiantes con promedio mayor o igual a 80 ---")
estudiantes_altos = df[df['promedio'] >= 80]
display(estudiantes_altos)

print("\n--- 7. Ordene estudiantes por promedio de mayor a menor ---")
df_ordenado = df.sort_values(by='promedio', ascending=False)
display(df_ordenado)

--- 3. Muestre las primeras 5 filas ---

     nombre     carrera  edad  promedio          ciudad
0    Carlos    Sistemas    21      85.5     Tegucigalpa
1       Ana    Medicina    23      92.0  San Pedro Sula
2      Luis    Sistemas    20      78.0     Tegucigalpa
3     Sofia     Derecho    22      88.5        La Ceiba
4  Fernando  Industrial    24      65.0       Choluteca

--- 4. Muestre la información general del DataFrame ---
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   nombre    10 non-null     str
 1   carrera   10 non-null     str
 2   edad      10 non-null     int64
 3   promedio  10 non-null     float64
 4   ciudad    10 non-null     str
dtypes: float64(1), int64(1), str(3)
memory usage: 532.0 bytes

--- 5. Calcule el promedio general de calificaciones ---
El promedio general de todos los estudiantes es: 83.90

--- 6. Muestre estudiantes con promedio mayor o igual a 80 ---

    nombre     carrera  edad  promedio          ciudad
0   Carlos    Sistemas    21      85.5     Tegucigalpa
1      Ana    Medicina    23      92.0  San Pedro Sula
3    Sofia     Derecho    22      88.5        La Ceiba
5    Maria    Medicina    21      90.0  San Pedro Sula
6    Jorge    Sistemas    22      81.5       Comayagua
8  Ricardo  Industrial    25      89.0        La Ceiba
9  Beatriz    Sistemas    23      95.5      Santa Rosa

--- 7. Ordene estudiantes por promedio de mayor a menor ---

     nombre     carrera  edad  promedio          ciudad
9   Beatriz    Sistemas    23      95.5      Santa Rosa
1       Ana    Medicina    23      92.0  San Pedro Sula
5     Maria    Medicina    21      90.0  San Pedro Sula
8   Ricardo  Industrial    25      89.0        La Ceiba
3     Sofia     Derecho    22      88.5        La Ceiba
0    Carlos    Sistemas    21      85.5     Tegucigalpa
6     Jorge    Sistemas    22      81.5       Comayagua
2      Luis    Sistemas    20      78.0     Tegucigalpa
7     Elena     Derecho    20      74.0     Tegucigalpa
4  Fernando  Industrial    24      65.0       Choluteca

# Ejercicio 17 Análisis de ventas con pandas

In [2]:
import pandas as pd

# Creamos las 15 ventas
datos_ventas = {
    'Fecha': ['2026-05-01', '2026-05-02', '2026-05-03', '2026-05-04', '2026-05-05', 
              '2026-05-06', '2026-05-07', '2026-05-08', '2026-05-09', '2026-05-10', 
              '2026-05-11', '2026-05-12', '2026-05-13', '2026-05-14', '2026-05-15'],
    'Vendedor': ['Carlos', 'Ana', 'Luis', 'Ana', 'Carlos', 
                 'Luis', 'Ana', 'Carlos', 'Luis', 'Ana', 
                 'Carlos', 'Luis', 'Ana', 'Carlos', 'Luis'],
    'Producto': ['Laptop', 'Mouse', 'Teclado', 'Monitor', 'Mouse', 
                 'Laptop', 'Teclado', 'Monitor', 'Laptop', 'Mouse', 
                 'Teclado', 'Monitor', 'Laptop', 'Teclado', 'Monitor'],
    'Categoria': ['Tecnología', 'Accesorios', 'Accesorios', 'Tecnología', 'Accesorios', 
                  'Tecnología', 'Accesorios', 'Tecnología', 'Tecnología', 'Accesorios', 
                  'Accesorios', 'Tecnología', 'Tecnología', 'Accesorios', 'Tecnología'],
    'Cantidad': [1, 5, 2, 1, 3, 2, 4, 1, 1, 6, 3, 2, 1, 2, 1],
    'Precio Unitario': [800, 20, 35, 150, 20, 800, 35, 150, 800, 20, 35, 150, 800, 35, 150]
}

# Convertimos los datos en una tabla
df = pd.DataFrame(datos_ventas)


df

         Fecha Vendedor Producto   Categoria  Cantidad  Precio Unitario
0   2026-05-01   Carlos   Laptop  Tecnología         1              800
1   2026-05-02      Ana    Mouse  Accesorios         5               20
2   2026-05-03     Luis  Teclado  Accesorios         2               35
3   2026-05-04      Ana  Monitor  Tecnología         1              150
4   2026-05-05   Carlos    Mouse  Accesorios         3               20
5   2026-05-06     Luis   Laptop  Tecnología         2              800
6   2026-05-07      Ana  Teclado  Accesorios         4               35
7   2026-05-08   Carlos  Monitor  Tecnología         1              150
8   2026-05-09     Luis   Laptop  Tecnología         1              800
9   2026-05-10      Ana    Mouse  Accesorios         6               20
10  2026-05-11   Carlos  Teclado  Accesorios         3               35
11  2026-05-12     Luis  Monitor  Tecnología         2              150
12  2026-05-13      Ana   Laptop  Tecnología         1              800
13  2026-05-14   Carlos  Teclado  Accesorios         2               35
14  2026-05-15     Luis  Monitor  Tecnología         1              150

In [3]:

df['TotalVenta'] = df['Cantidad'] * df['Precio Unitario']


df

,Fecha,Vendedor,Producto,Categoria,Cantidad,Precio Unitario,TotalVenta
0,2026-05-01,Carlos,Laptop,Tecnología,1,800,800
1,2026-05-02,Ana,Mouse,Accesorios,5,20,100
2,2026-05-03,Luis,Teclado,Accesorios,2,35,70
3,2026-05-04,Ana,Monitor,Tecnología,1,150,150
4,2026-05-05,Carlos,Mouse,Accesorios,3,20,60
5,2026-05-06,Luis,Laptop,Tecnología,2,800,1600
6,2026-05-07,Ana,Teclado,Accesorios,4,35,140
7,2026-05-08,Carlos,Monitor,Tecnología,1,150,150
8,2026-05-09,Luis,Laptop,Tecnología,1,800,800
9,2026-05-10,Ana,Mouse,Accesorios,6,20,120
10,2026-05-11,Carlos,Teclado,Accesorios,3,35,105
11,2026-05-12,Luis,Monitor,Tecnología,2,150,300
12,2026-05-13,Ana,Laptop,Tecnología,1,800,800
13,2026-05-14,Carlos,Teclado,Accesorios,2,35,70
14,2026-05-15,Luis,Monitor,Tecnología,1,150,150

In [7]:

print("Total vendido por vendedor")
total_por_vendedor = df.groupby('Vendedor')['TotalVenta'].sum()
print(total_por_vendedor)
print("\n")

print("Producto más vendido")
producto_mas_vendido = df.groupby('Producto')['Cantidad'].sum().idxmax()
print(f"El producto del que se vendieron más unidades es: {producto_mas_vendido}")
print("\n")

print("Categoría con mayor ingreso")
categoria_mayor_ingreso = df.groupby('Categoria')['TotalVenta'].sum().idxmax()
print(f"La categoría que generó más dinero es: {categoria_mayor_ingreso}")
print("\n")

print("Ventas ordenadas de mayor a menor")
df_ordenado = df.sort_values(by='TotalVenta', ascending=False)
df_ordenado

Total vendido por vendedor
Vendedor
Ana       1310
Carlos    1185
Luis      2920
Name: TotalVenta, dtype: int64


Producto más vendido
El producto del que se vendieron más unidades es: Mouse


Categoría con mayor ingreso
La categoría que generó más dinero es: Tecnología


Ventas ordenadas de mayor a menor

,Fecha,Vendedor,Producto,Categoria,Cantidad,Precio Unitario,TotalVenta
5,2026-05-06,Luis,Laptop,Tecnología,2,800,1600
0,2026-05-01,Carlos,Laptop,Tecnología,1,800,800
8,2026-05-09,Luis,Laptop,Tecnología,1,800,800
12,2026-05-13,Ana,Laptop,Tecnología,1,800,800
11,2026-05-12,Luis,Monitor,Tecnología,2,150,300
7,2026-05-08,Carlos,Monitor,Tecnología,1,150,150
3,2026-05-04,Ana,Monitor,Tecnología,1,150,150
14,2026-05-15,Luis,Monitor,Tecnología,1,150,150
6,2026-05-07,Ana,Teclado,Accesorios,4,35,140
9,2026-05-10,Ana,Mouse,Accesorios,6,20,120
10,2026-05-11,Carlos,Teclado,Accesorios,3,35,105
1,2026-05-02,Ana,Mouse,Accesorios,5,20,100
2,2026-05-03,Luis,Teclado,Accesorios,2,35,70
13,2026-05-14,Carlos,Teclado,Accesorios,2,35,70
4,2026-05-05,Carlos,Mouse,Accesorios,3,20,60

# Ejercicio 18 Limpieza de datos con pandas

In [4]:
# Ejercicio 18: Limpieza de datos con pandas
import pandas as pd
clientes = [
    {"nombre": "Tommy Vega", "edad": 30, "email": None, "ciudad": "San Pedro Sula", "telefono": "98765432"},
    {"nombre": "Nelsy Alonzo", "edad": 24, "email": "nelsy.alonzo@gmail.com", "ciudad": "Puerto Cortés", "telefono": None},
    {"nombre": "Marlon Rivera", "edad": 29, "email": "marlon.rivera@gmail.com", "ciudad": None, "telefono": "92366718"}
]

df_clientes = pd.DataFrame(clientes)

print(df_clientes.isnull().sum())

print("\nValores nulos:", df_clientes[df_clientes.isnull().any(axis=1)].shape[0])

df_clientes["ciudad"] = df_clientes["ciudad"].fillna("No especificada")

df_limpio = df_clientes.dropna(subset=["email"])

display(df_limpio)

# La lógica en este ejercicio es crear primero un diccionario de los clientes y luego pasarlo a un DataFrame, posterior a ello se solicitan varias cosas
# Con la función isnull() se identifican lso valores nulos, y luego solo se cuentan con la funcion de sum()
# Luego para contar los valores nulos por columna se utiliza la misma funcion de isnull() pero con un filtro para contar solo las filas que tengan al menos un valor nulo
# Ya con la funciona fillna() se reemplaza el valor nulo de la columna ciudad por "No especificada"
# Y por último con la función dropna() se eliminan las filas que tengan un valor nulo en la columna email

nombre      0
edad        0
email       1
ciudad      1
telefono    1
dtype: int64

Valores nulos: 3

          nombre  edad                    email           ciudad  telefono
1   Nelsy Alonzo    24   nelsy.alonzo@gmail.com    Puerto Cortés       NaN
2  Marlon Rivera    29  marlon.rivera@gmail.com  No especificada  92366718

# Ejercicio 19

In [6]:
import pandas as pd
datos_prestamos = {
    "cliente":         ["Ana Torres", "Luis Mejia", "Maria Paz", "Carlos Vega",
                        "Sofia Ruiz", "Jorge Lima", "Valeria Cruz", "Diego Reyes",
                        "Fernanda Lopez", "Andres Diaz"],
    "monto_solicitado":[45000, 75000, 30000, 120000, 55000,
                        20000, 90000, 48000, 65000, 15000],
    "plazo_meses":     [24, 36, 12, 48, 24, 12, 36, 24, 36, 12],
    "ingreso_mensual": [18000, 25000, 12000, 40000, 20000,
                        9000, 35000, 17000, 22000, 8000],
    "estado":          ["Aprobado", "Aprobado", "Rechazado", "Aprobado",
                        "En revision", "Rechazado", "Aprobado", "En revision",
                        "Aprobado", "Rechazado"]
}

df_pre = pd.DataFrame(datos_prestamos)
print("DataFrame de prestamos:")
print(df_pre)

print(f"\nMonto promedio solicitado: L.{df_pre['monto_solicitado'].mean():,.2f}")

print("\nConteo de solicitudes por estado:")
print(df_pre["estado"].value_counts())

print("\nPrestamos aprobados:")
print(df_pre[df_pre["estado"] == "Aprobado"])

print("\nClientes con monto mayor a L.50,000:")
print(df_pre[df_pre["monto_solicitado"] > 50000])

print("\nPromedio de monto solicitado por estado:")
print(df_pre.groupby("estado")["monto_solicitado"].mean().reset_index())

DataFrame de prestamos:
          cliente  monto_solicitado  plazo_meses  ingreso_mensual       estado
0      Ana Torres             45000           24            18000     Aprobado
1      Luis Mejia             75000           36            25000     Aprobado
2       Maria Paz             30000           12            12000    Rechazado
3     Carlos Vega            120000           48            40000     Aprobado
4      Sofia Ruiz             55000           24            20000  En revision
5      Jorge Lima             20000           12             9000    Rechazado
6    Valeria Cruz             90000           36            35000     Aprobado
7     Diego Reyes             48000           24            17000  En revision
8  Fernanda Lopez             65000           36            22000     Aprobado
9     Andres Diaz             15000           12             8000    Rechazado

Monto promedio solicitado: L.56,300.00

Conteo de solicitudes por estado:
estado
Aprobado       5
Rechazado      3
En revision    2
Name: count, dtype: int64

Prestamos aprobados:
          cliente  monto_solicitado  plazo_meses  ingreso_mensual    estado
0      Ana Torres             45000           24            18000  Aprobado
1      Luis Mejia             75000           36            25000  Aprobado
3     Carlos Vega            120000           48            40000  Aprobado
6    Valeria Cruz             90000           36            35000  Aprobado
8  Fernanda Lopez             65000           36            22000  Aprobado

Clientes con monto mayor a L.50,000:
          cliente  monto_solicitado  plazo_meses  ingreso_mensual       estado
1      Luis Mejia             75000           36            25000     Aprobado
3     Carlos Vega            120000           48            40000     Aprobado
4      Sofia Ruiz             55000           24            20000  En revision
6    Valeria Cruz             90000           36            35000     Aprobado
8  Fernanda Lopez             65000           36            22000     Aprobado

Promedio de monto solicitado por estado:
        estado  monto_solicitado
0     Aprobado      79000.000000
1  En revision      51500.000000
2    Rechazado      21666.666667

# Ejercicio 20 Mini analisis de datos

In [3]:
# Ejercicio 20: Mini análisis de datos tipo empresa
import pandas as pd
empleados = [
    {"nombre": "Tommy Vega", "departamento": "IT", "cargo": "Analista de Sistemas", "salario": 33000, "años_experiencia": 7, "ciudad": "San Pedro Sula"},
    {"nombre": "Nelsy Alonzo", "departamento": "Operaciones", "cargo": "Especialista en Digitación", "salario": 18000, "años_experiencia": 2, "ciudad": "Puerto Cortés"},
    {"nombre": "Marlon Rivera", "departamento": "IT", "cargo": "Desarrollador Senior", "salario": 42000, "años_experiencia": 6, "ciudad": "San Pedro Sula"}
 ]

df_empleados = pd.DataFrame(empleados)
display(df_empleados)

print("\nEstadísticas generales de salarios")
estadisticas_salarios = df_empleados["salario"].describe()
display(estadisticas_salarios)

print("\nSalario promedio por departamento")
promedio_por_depto = df_empleados.groupby("departamento")["salario"].mean()
display(promedio_por_depto)

print("\nEmpleado con salario más alto")
top_empleado = df_empleados.loc[df_empleados["salario"].idxmax()]
display(top_empleado)

print("\nEmpleados con más de 5 años de experiencia")
df_mas_experiencia = df_empleados[df_empleados["años_experiencia"] > 5]
display(df_mas_experiencia)

print("\nEmpleados ordenados por salario")
df_ordenado = df_empleados.sort_values(by="salario", ascending=False)
display(df_ordenado)

def nivel_experiencia(años):
    if años < 1:
        return "Junior"
    elif años <= 3:
        return "Intermedio"
    else:
        return "Senior"

df_empleados["NivelExperiencia"] = df_empleados["años_experiencia"].apply(nivel_experiencia)
display(df_empleados)

# La lógica en este ejercicio de igual forma se basa en crear un diccionario primero y luego convertirlo a un DataFrame
# Luego con la funcion de describe() se pueden obtener las estadisticas generales de la columna de salarios
# Para el salario promerio por departamente se utiliza primero la funcion groupby() y luego se obtiene el promedio con la funcion mean()
# Para obtener el empleado con el salario mas alto se utilia la funcion idxmx() que nos permite por medio del id obtener el salario mas alto de X empleado
# y utilizando la funcion loc() se obttiene toda la fila del empleado
# La del empeado con mas de 5 años de experiencia simplemente se evalua la columan de años de experiencia que sea mayor a 5
# Para ordenar los empleados por salario, se utiliza la funcion sort_values() y se ordena de forma descendente
# Y ya por último creamos primero la defincion para saber que se considera Junior, Interemedio o Senior, luego ya con la funcion apply() se aplica esa función 
# a la columna de años de experiencia para crear una nueva columna con el nivel de experiencia de cada empleado

,nombre,departamento,cargo,salario,años_experiencia,ciudad
0,Tommy Vega,IT,Analista de Sistemas,33000,7,San Pedro Sula
1,Nelsy Alonzo,Operaciones,Especialista en Digitación,18000,2,Puerto Cortés
2,Marlon Rivera,IT,Desarrollador Senior,42000,6,San Pedro Sula

Estadísticas generales de salarios

count        3.000000
mean     31000.000000
std      12124.355653
min      18000.000000
25%      25500.000000
50%      33000.000000
75%      37500.000000
max      42000.000000
Name: salario, dtype: float64

Salario promedio por departamento

departamento
IT             37500.0
Operaciones    18000.0
Name: salario, dtype: float64

Empleado con salario más alto

nombre                     Marlon Rivera
departamento                          IT
cargo               Desarrollador Senior
salario                            42000
años_experiencia                       6
ciudad                    San Pedro Sula
Name: 2, dtype: object

Empleados con más de 5 años de experiencia

,nombre,departamento,cargo,salario,años_experiencia,ciudad
0,Tommy Vega,IT,Analista de Sistemas,33000,7,San Pedro Sula
2,Marlon Rivera,IT,Desarrollador Senior,42000,6,San Pedro Sula

Empleados ordenados por salario

,nombre,departamento,cargo,salario,años_experiencia,ciudad
2,Marlon Rivera,IT,Desarrollador Senior,42000,6,San Pedro Sula
0,Tommy Vega,IT,Analista de Sistemas,33000,7,San Pedro Sula
1,Nelsy Alonzo,Operaciones,Especialista en Digitación,18000,2,Puerto Cortés

,nombre,departamento,cargo,salario,años_experiencia,ciudad,NivelExperiencia
0,Tommy Vega,IT,Analista de Sistemas,33000,7,San Pedro Sula,Senior
1,Nelsy Alonzo,Operaciones,Especialista en Digitación,18000,2,Puerto Cortés,Intermedio
2,Marlon Rivera,IT,Desarrollador Senior,42000,6,San Pedro Sula,Senior